"""
Decision Tree Scenarios for the LegalAce Wizard — Module 4.

Each scenario contains:
  - metadata (id, category, title, icon, multilingual labels)
  - questions (decision tree nodes)
  - action_plans (keyed by answer path hash or special keys)

Action plan selection logic is in service.py.
"""
from __future__ import annotations

# ---------------------------------------------------------------------------
# Categories
# ---------------------------------------------------------------------------
CATEGORIES = [
    {"id": "housing",    "name": "Housing & Renting",  "name_ta": "வீட்டு வாடகை",       "name_hi": "आवास और किराया",    "icon": "🏠", "color": "#10b981", "scenario_count": 3},
    {"id": "employment", "name": "Employment",          "name_ta": "வேலைவாய்ப்பு",        "name_hi": "रोजगार",            "icon": "💼", "color": "#3b82f6", "scenario_count": 3},
    {"id": "consumer",   "name": "Consumer Rights",     "name_ta": "நுகர்வோர் உரிமைகள்", "name_hi": "उपभोक्ता अधिकार",  "icon": "🛒", "color": "#f59e0b", "scenario_count": 3},
    {"id": "banking",    "name": "Banking & UPI",       "name_ta": "வங்கி மற்றும் UPI",   "name_hi": "बैंकिंग और UPI",   "icon": "🏦", "color": "#06b6d4", "scenario_count": 2},
    {"id": "cyber",      "name": "Cyber Crime",         "name_ta": "சைபர் குற்றம்",       "name_hi": "साइबर अपराध",      "icon": "💻", "color": "#8b5cf6", "scenario_count": 3},
    {"id": "traffic",    "name": "Traffic & Road",      "name_ta": "போக்குவரத்து",        "name_hi": "यातायात और सड़क",  "icon": "🚗", "color": "#f43f5e", "scenario_count": 2},
    {"id": "women",      "name": "Women Safety",        "name_ta": "பெண்கள் பாதுகாப்பு", "name_hi": "महिला सुरक्षा",    "icon": "👩", "color": "#a855f7", "scenario_count": 2},
    {"id": "education",  "name": "Education Rights",    "name_ta": "கல்வி உரிமைகள்",     "name_hi": "शिक्षा अधिकार",   "icon": "🎓", "color": "#14b8a6", "scenario_count": 2},
    {"id": "cheque_debt","name": "Cheque Bounce & Debt","name_ta": "செக் திரும்பல்",      "name_hi": "चेक बाउंस और ऋण", "icon": "💳", "color": "#ef4444", "scenario_count": 1},
    {"id": "rti",        "name": "RTI & Public Service","name_ta": "RTI விண்ணப்பம்",    "name_hi": "RTI और लोक सेवा", "icon": "📜", "color": "#f97316", "scenario_count": 1},
    {"id": "real_estate","name": "RERA Real Estate",    "name_ta": "ரியல் எஸ்டேட்",       "name_hi": "रेरा रियल एस्टेट",  "icon": "🏢", "color": "#6366f1", "scenario_count": 1},
    {"id": "insurance",  "name": "Insurance & Health",  "name_ta": "காப்பீடு கோரிக்கை",  "name_hi": "बीमा और स्वास्थ्य", "icon": "🏥", "color": "#ec4899", "scenario_count": 1},
    {"id": "family",     "name": "Family & Support",    "name_ta": "குடும்ப உதவிகள்",   "name_hi": "परिवार और पोषण",   "icon": "👨‍👩‍👧", "color": "#84cc16", "scenario_count": 1},
]

# ---------------------------------------------------------------------------
# Scenario Registry
# ---------------------------------------------------------------------------
SCENARIOS: list[dict] = [

    # ===== HOUSING =====
    {
        "scenario_id": "housing_deposit",
        "category": "housing",
        "title": "Landlord not returning deposit",
        "title_ta": "வீட்டு உரிமையாளர் வைப்பு திரும்ப தரவில்லை",
        "title_hi": "मकान मालिक जमा राशि वापस नहीं कर रहा",
        "icon": "💰",
        "questions": [
            {"id": "q1", "text": "Have you vacated and handed over the property?",
             "text_ta": "நீங்கள் வீட்டை காலி செய்து ஒப்படைத்தீர்களா?",
             "text_hi": "क्या आपने संपत्ति खाली कर दी है?",
             "type": "boolean"},
            {"id": "q2", "text": "Has it been more than 21 days since vacating?",
             "text_ta": "காலி செய்து 21 நாட்களுக்கு மேல் ஆகிவிட்டதா?",
             "text_hi": "क्या खाली किए हुए 21 दिन से अधिक हो गए हैं?",
             "type": "boolean"},
            {"id": "q3", "text": "Did the landlord give any written reason for withholding?",
             "text_ta": "வீட்டு உரிமையாளர் தடுத்து வைப்பதற்கான காரணம் எழுத்தில் கொடுத்தாரா?",
             "text_hi": "क्या मकान मालिक ने रोकने का कारण लिखित में दिया?",
             "type": "boolean"},
            {"id": "q4", "text": "Do you have the original rent agreement?",
             "text_ta": "உங்களிடம் அசல் வாடகை ஒப்பந்தம் உள்ளதா?",
             "text_hi": "क्या आपके पास मूल किराया समझौता है?",
             "type": "boolean"},
        ],
    },
    {
        "scenario_id": "housing_eviction",
        "category": "housing",
        "title": "Illegal eviction by landlord",
        "title_ta": "சட்டவிரோதமான வெளியேற்றம்",
        "title_hi": "मकान मालिक द्वारा अवैध बेदखली",
        "icon": "🚪",
        "questions": [
            {"id": "q1", "text": "Did you receive a formal written eviction notice?",
             "text_ta": "உங்களுக்கு அதிகாரப்பூர்வ வெளியேற்றல் நோட்டீஸ் கிடைத்ததா?",
             "text_hi": "क्या आपको औपचारिक बेदखली नोटिस मिला?",
             "type": "boolean"},
            {"id": "q2", "text": "Is your rent payment up to date?",
             "text_ta": "உங்கள் வாடகை பணம் தவணை செலுத்தப்பட்டுள்ளதா?",
             "text_hi": "क्या आपका किराया भुगतान अद्यतित है?",
             "type": "boolean"},
            {"id": "q3", "text": "Has the landlord changed locks or removed belongings?",
             "text_ta": "வீட்டு உரிமையாளர் பூட்டுகளை மாற்றினாரா அல்லது உடைமைகளை அகற்றினாரா?",
             "text_hi": "क्या मकान मालिक ने ताले बदले या सामान हटाया?",
             "type": "boolean"},
        ],
    },
    {
        "scenario_id": "housing_rent_hike",
        "category": "housing",
        "title": "Landlord demanding excess rent",
        "title_ta": "அதிகமான வாடகை கோரிக்கை",
        "title_hi": "मकान मालिक अत्यधिक किराया मांग रहा है",
        "icon": "📈",
        "questions": [
            {"id": "q1", "text": "Is the rent increase more than 10% per year?",
             "text_ta": "வாடகை உயர்வு ஆண்டுக்கு 10%க்கும் அதிகமா?",
             "text_hi": "क्या किराया वृद्धि प्रति वर्ष 10% से अधिक है?",
             "type": "boolean"},
            {"id": "q2", "text": "Do you have a registered rent agreement?",
             "text_ta": "உங்களிடம் பதிவு செய்யப்பட்ட வாடகை ஒப்பந்தம் உள்ளதா?",
             "text_hi": "क्या आपके पास पंजीकृत किराया समझौता है?",
             "type": "boolean"},
            {"id": "q3", "text": "Did the landlord give 3 months' written notice before the hike?",
             "text_ta": "வீட்டு உரிமையாளர் உயர்வுக்கு முன் 3 மாத எழுத்துறு நோட்டீஸ் கொடுத்தாரா?",
             "text_hi": "क्या मकान मालिक ने वृद्धि से पहले 3 महीने का नोटिस दिया?",
             "type": "boolean"},
        ],
    },

    # ===== EMPLOYMENT =====
    {
        "scenario_id": "employment_salary",
        "category": "employment",
        "title": "Employer not paying salary",
        "title_ta": "நிறுவனம் சம்பளம் தராமல் இருக்கிறது",
        "title_hi": "नियोक्ता वेतन नहीं दे रहा",
        "icon": "💵",
        "questions": [
            {"id": "q1", "text": "How many months of salary is overdue?",
             "text_ta": "எத்தனை மாத சம்பளம் நிலுவையில் உள்ளது?",
             "text_hi": "कितने महीनों का वेतन बकाया है?",
             "type": "choice",
             "options": ["1 month", "2-3 months", "More than 3 months"]},
            {"id": "q2", "text": "Do you have a written employment contract?",
             "text_ta": "உங்களிடம் எழுத்துறு வேலை ஒப்பந்தம் உள்ளதா?",
             "text_hi": "क्या आपके पास लिखित नियुक्ति अनुबंध है?",
             "type": "boolean"},
            {"id": "q3", "text": "Have you complained to HR or management in writing?",
             "text_ta": "நீங்கள் HR அல்லது நிர்வாகத்திடம் எழுத்தில் புகாரளித்தீர்களா?",
             "text_hi": "क्या आपने HR या प्रबंधन को लिखित में शिकायत की है?",
             "type": "boolean"},
            {"id": "q4", "text": "Are you still employed at this company?",
             "text_ta": "நீங்கள் இன்னும் இந்த நிறுவனத்தில் பணிபுரிகிறீர்களா?",
             "text_hi": "क्या आप अभी भी इस कंपनी में कार्यरत हैं?",
             "type": "boolean"},
        ],
    },
    {
        "scenario_id": "employment_termination",
        "category": "employment",
        "title": "Wrongful or sudden termination",
        "title_ta": "தவறான அல்லது திடீர் பணிநீக்கம்",
        "title_hi": "गलत या अचानक बर्खास्तगी",
        "icon": "🚫",
        "questions": [
            {"id": "q1", "text": "Did you receive any written termination letter?",
             "text_ta": "உங்களுக்கு எழுத்துறு பணிநீக்கக் கடிதம் கிடைத்ததா?",
             "text_hi": "क्या आपको कोई लिखित बर्खास्तगी पत्र मिला?",
             "type": "boolean"},
            {"id": "q2", "text": "Did you complete more than 1 year of continuous service?",
             "text_ta": "நீங்கள் 1 ஆண்டுக்கும் மேல் தொடர்ச்சியான சேவை செய்தீர்களா?",
             "text_hi": "क्या आपने 1 वर्ष से अधिक निरंतर सेवा पूरी की?",
             "type": "boolean"},
            {"id": "q3", "text": "Were you given 1 month notice or payment in lieu?",
             "text_ta": "உங்களுக்கு 1 மாத நோட்டீஸ் அல்லது அதற்கு இணையான தொகை தரப்பட்டதா?",
             "text_hi": "क्या आपको 1 महीने की नोटिस या उसके बदले भुगतान दिया गया?",
             "type": "boolean"},
            {"id": "q4", "text": "Was retrenchment compensation paid (15 days per year)?",
             "text_ta": "ஓய்வூதிய ஈடு தொகை (ஆண்டுக்கு 15 நாட்கள்) வழங்கப்பட்டதா?",
             "text_hi": "क्या छंटनी मुआवजा (प्रति वर्ष 15 दिन) दिया गया?",
             "type": "boolean"},
        ],
    },
    {
        "scenario_id": "employment_pf",
        "category": "employment",
        "title": "PF / EPF not deposited by employer",
        "title_ta": "பி.எஃப் கட்டணம் வழங்கப்படவில்லை",
        "title_hi": "नियोक्ता ने PF/EPF जमा नहीं किया",
        "icon": "📋",
        "questions": [
            {"id": "q1", "text": "Is PF being deducted from your salary?",
             "text_ta": "உங்கள் சம்பளத்திலிருந்து பி.எஃப் கழிக்கப்படுகிறதா?",
             "text_hi": "क्या आपके वेतन से PF कटौती की जा रही है?",
             "type": "boolean"},
            {"id": "q2", "text": "Have you checked your UAN passbook for deposits?",
             "text_ta": "நீங்கள் UAN பாஸ்புக்கில் வைப்புகளை சரிபார்த்தீர்களா?",
             "text_hi": "क्या आपने जमा के लिए UAN पासबुक जांची है?",
             "type": "boolean"},
            {"id": "q3", "text": "Have you been employed here for more than 6 months?",
             "text_ta": "நீங்கள் இங்கு 6 மாதங்களுக்கும் மேல் பணிபுரிந்தீர்களா?",
             "text_hi": "क्या आप यहाँ 6 महीने से अधिक समय से कार्यरत हैं?",
             "type": "boolean"},
        ],
    },

    # ===== CONSUMER =====
    {
        "scenario_id": "consumer_defective",
        "category": "consumer",
        "title": "Defective product / service",
        "title_ta": "குறைபாடுள்ள பொருள் / சேவை",
        "title_hi": "दोषपूर्ण उत्पाद / सेवा",
        "icon": "📦",
        "questions": [
            {"id": "q1", "text": "When did you purchase this product or service?",
             "text_ta": "நீங்கள் இந்த பொருளை / சேவையை எப்போது வாங்கினீர்கள்?",
             "text_hi": "आपने यह उत्पाद या सेवा कब खरीदी?",
             "type": "choice",
             "options": ["Within 30 days", "1-6 months ago", "6 months - 2 years ago", "More than 2 years ago"]},
            {"id": "q2", "text": "Did you contact the seller or company for replacement/refund?",
             "text_ta": "நீங்கள் மாற்று / திரும்பப் பெறுவதற்கு விற்பனையாளரை தொடர்பு கொண்டீர்களா?",
             "text_hi": "क्या आपने बदलाव/वापसी के लिए विक्रेता से संपर्क किया?",
             "type": "boolean"},
            {"id": "q3", "text": "Did you get a bill or receipt?",
             "text_ta": "உங்களிடம் பில் அல்லது ரசீது உள்ளதா?",
             "text_hi": "क्या आपके पास बिल या रसीद है?",
             "type": "boolean"},
            {"id": "q4", "text": "Is the product under warranty?",
             "text_ta": "பொருள் உத்தரவாதத்தின் கீழ் உள்ளதா?",
             "text_hi": "क्या उत्पाद वारंटी में है?",
             "type": "boolean"},
        ],
    },
    {
        "scenario_id": "consumer_refund",
        "category": "consumer",
        "title": "Refund denied by seller/platform",
        "title_ta": "திரும்பப் பெறுதல் மறுக்கப்பட்டது",
        "title_hi": "विक्रेता ने रिफंड से इनकार किया",
        "icon": "↩️",
        "questions": [
            {"id": "q1", "text": "Is this an online or offline purchase?",
             "text_ta": "இது ஆன்லைன் அல்லது ஆஃப்லைன் கொள்முதலா?",
             "text_hi": "क्या यह ऑनलाइन या ऑफलाइन खरीद है?",
             "type": "choice",
             "options": ["Online (Amazon/Flipkart etc.)", "Offline (shop/store)", "Service provider"]},
            {"id": "q2", "text": "Have you raised a complaint via the platform/company?",
             "text_ta": "நீங்கள் தளம் / நிறுவனம் வழியாக புகாரளித்தீர்களா?",
             "text_hi": "क्या आपने प्लेटफॉर्म/कंपनी के माध्यम से शिकायत की है?",
             "type": "boolean"},
            {"id": "q3", "text": "Did you get a written rejection of your refund?",
             "text_ta": "உங்கள் திரும்பப் பெறுதல் மறுப்பு எழுத்தில் கிடைத்ததா?",
             "text_hi": "क्या आपको लिखित में रिफंड अस्वीकृति मिली?",
             "type": "boolean"},
        ],
    },
    {
        "scenario_id": "consumer_overcharge",
        "category": "consumer",
        "title": "Charged more than MRP / hidden fees",
        "title_ta": "MRP விட அதிகமாக வசூலிக்கப்பட்டது",
        "title_hi": "MRP से अधिक शुल्क / छिपे हुए शुल्क",
        "icon": "💸",
        "questions": [
            {"id": "q1", "text": "Do you have the bill or receipt showing overcharge?",
             "text_ta": "அதிகமான கட்டணம் காட்டும் பில் அல்லது ரசீது உள்ளதா?",
             "text_hi": "क्या आपके पास अधिक शुल्क दिखाने वाला बिल है?",
             "type": "boolean"},
            {"id": "q2", "text": "Is the MRP printed on the product packaging?",
             "text_ta": "MRP தயாரிப்பு பொதியில் அச்சிடப்பட்டுள்ளதா?",
             "text_hi": "क्या MRP उत्पाद पैकेजिंग पर मुद्रित है?",
             "type": "boolean"},
            {"id": "q3", "text": "Did the seller refuse to correct when pointed out?",
             "text_ta": "சுட்டிக்காட்டியபோது விற்பனையாளர் திருத்த மறுத்தாரா?",
             "text_hi": "क्या विक्रेता ने बताने पर सुधार करने से इनकार किया?",
             "type": "boolean"},
        ],
    },

    # ===== BANKING =====
    {
        "scenario_id": "banking_upi_fraud",
        "category": "banking",
        "title": "UPI / Online payment fraud",
        "title_ta": "UPI / ஆன்லைன் பணம் மோசடி",
        "title_hi": "UPI / ऑनलाइन भुगतान धोखाधड़ी",
        "icon": "📱",
        "questions": [
            {"id": "q1", "text": "When did the fraud occur?",
             "text_ta": "மோசடி எப்போது நடந்தது?",
             "text_hi": "धोखाधड़ी कब हुई?",
             "type": "choice",
             "options": ["Today", "Within 3 days", "4-30 days ago", "More than 30 days ago"]},
            {"id": "q2", "text": "Did you share your OTP or PIN with anyone?",
             "text_ta": "நீங்கள் உங்கள் OTP அல்லது PIN யாரிடமாவது பகிர்ந்தீர்களா?",
             "text_hi": "क्या आपने किसी के साथ OTP या PIN साझा किया?",
             "type": "boolean"},
            {"id": "q3", "text": "Have you already blocked your card/UPI account?",
             "text_ta": "நீங்கள் ஏற்கனவே உங்கள் கார்டு/UPI கணக்கை தடுத்தீர்களா?",
             "text_hi": "क्या आपने अपना कार्ड/UPI खाता पहले ही ब्लॉक कर लिया है?",
             "type": "boolean"},
            {"id": "q4", "text": "Have you reported to your bank?",
             "text_ta": "நீங்கள் உங்கள் வங்கியிடம் தெரிவித்தீர்களா?",
             "text_hi": "क्या आपने अपने बैंक को सूचित किया है?",
             "type": "boolean"},
        ],
    },
    {
        "scenario_id": "banking_loan",
        "category": "banking",
        "title": "Unfair loan terms / recovery harassment",
        "title_ta": "நியாயமற்ற கடன் நிபந்தனைகள் / வசூல் துன்புறுத்தல்",
        "title_hi": "अनुचित ऋण शर्तें / वसूली उत्पीड़न",
        "icon": "🏦",
        "questions": [
            {"id": "q1", "text": "Are recovery agents visiting your home or workplace?",
             "text_ta": "வசூல் முகவர்கள் உங்கள் வீடு அல்லது பணியிடத்திற்கு வருகிறார்களா?",
             "text_hi": "क्या वसूली एजेंट आपके घर या कार्यस्थल पर आ रहे हैं?",
             "type": "boolean"},
            {"id": "q2", "text": "Are they calling between 7 AM and 7 PM only?",
             "text_ta": "அவர்கள் காலை 7 மணி முதல் மாலை 7 மணி வரை மட்டும் அழைக்கிறார்களா?",
             "text_hi": "क्या वे केवल सुबह 7 बजे से शाम 7 बजे के बीच कॉल कर रहे हैं?",
             "type": "boolean"},
            {"id": "q3", "text": "Have you received loan documents with full terms?",
             "text_ta": "நீங்கள் முழு நிபந்தனைகளுடன் கடன் ஆவணங்களை பெற்றீர்களா?",
             "text_hi": "क्या आपको पूरी शर्तों के साथ ऋण दस्तावेज मिले हैं?",
             "type": "boolean"},
        ],
    },

    # ===== CYBER CRIME =====
    {
        "scenario_id": "cyber_fraud",
        "category": "cyber",
        "title": "Online fraud / money stolen digitally",
        "title_ta": "ஆன்லைன் மோசடி / டிஜிட்டல் பணம் திருடப்பட்டது",
        "title_hi": "ऑनलाइन धोखाधड़ी / डिजिटल धन चोरी",
        "icon": "🎣",
        "questions": [
            {"id": "q1", "text": "Did you click a suspicious link or install an unknown app?",
             "text_ta": "நீங்கள் சந்தேகமான இணைப்பை கிளிக் செய்தீர்களா அல்லது தெரியாத ஆப்பை நிறுவினீர்களா?",
             "text_hi": "क्या आपने संदिग्ध लिंक क्लिक किया या अज्ञात ऐप इंस्टॉल किया?",
             "type": "boolean"},
            {"id": "q2", "text": "Was money transferred from your account?",
             "text_ta": "உங்கள் கணக்கிலிருந்து பணம் மாற்றப்பட்டதா?",
             "text_hi": "क्या आपके खाते से पैसे ट्रांसफर हुए?",
             "type": "boolean"},
            {"id": "q3", "text": "Do you have screenshots or evidence of the fraud?",
             "text_ta": "மோசடியின் ஸ்கிரீன்ஷாட் அல்லது ஆதாரம் உங்களிடம் உள்ளதா?",
             "text_hi": "क्या आपके पास धोखाधड़ी के स्क्रीनशॉट या सबूत हैं?",
             "type": "boolean"},
        ],
    },
    {
        "scenario_id": "cyber_harassment",
        "category": "cyber",
        "title": "Online harassment / stalking",
        "title_ta": "ஆன்லைன் துன்புறுத்தல் / பின்தொடர்தல்",
        "title_hi": "ऑनलाइन उत्पीड़न / पीछा करना",
        "icon": "👁️",
        "questions": [
            {"id": "q1", "text": "Is the harasser known to you personally?",
             "text_ta": "துன்புறுத்துபவர் உங்களுக்கு தனிப்பட்ட முறையில் தெரிந்தவரா?",
             "text_hi": "क्या उत्पीड़क आपको व्यक्तिगत रूप से जानता है?",
             "type": "boolean"},
            {"id": "q2", "text": "Have they posted private photos or videos without consent?",
             "text_ta": "அவர்கள் அனுமதியின்றி தனிப்பட்ட புகைப்படங்கள் அல்லது வீடியோக்களை பதிவிட்டார்களா?",
             "text_hi": "क्या उन्होंने बिना अनुमति के निजी फोटो या वीडियो पोस्ट किए?",
             "type": "boolean"},
            {"id": "q3", "text": "Have you documented / saved the messages as evidence?",
             "text_ta": "நீங்கள் செய்திகளை ஆதாரமாக சேகரித்து வைத்தீர்களா?",
             "text_hi": "क्या आपने संदेशों को सबूत के रूप में दस्तावेजीकरण/सहेजा है?",
             "type": "boolean"},
        ],
    },
    {
        "scenario_id": "cyber_identity",
        "category": "cyber",
        "title": "Identity theft / fake account",
        "title_ta": "அடையாள திருட்டு / போலி கணக்கு",
        "title_hi": "पहचान की चोरी / नकली खाता",
        "icon": "🪪",
        "questions": [
            {"id": "q1", "text": "Has someone created a fake social media profile using your details?",
             "text_ta": "யாரோ உங்கள் விவரங்களைப் பயன்படுத்தி போலி சமூக ஊடக சுயவிவரத்தை உருவாக்கியிருக்கிறார்களா?",
             "text_hi": "क्या किसी ने आपकी जानकारी का उपयोग करके नकली सोशल मीडिया प्रोफाइल बनाई?",
             "type": "boolean"},
            {"id": "q2", "text": "Have loans or financial accounts been opened in your name?",
             "text_ta": "உங்கள் பெயரில் கடன்கள் அல்லது நிதி கணக்குகள் திறக்கப்பட்டுள்ளனவா?",
             "text_hi": "क्या आपके नाम से ऋण या वित्तीय खाते खोले गए हैं?",
             "type": "boolean"},
            {"id": "q3", "text": "Have you already reported to the platform?",
             "text_ta": "நீங்கள் ஏற்கனவே தளத்தில் புகாரளித்தீர்களா?",
             "text_hi": "क्या आपने पहले ही प्लेटफॉर्म को रिपोर्ट किया है?",
             "type": "boolean"},
        ],
    },

    # ===== TRAFFIC =====
    {
        "scenario_id": "traffic_accident",
        "category": "traffic",
        "title": "Road accident — compensation claim",
        "title_ta": "சாலை விபத்து — இழப்பீடு கோரிக்கை",
        "title_hi": "सड़क दुर्घटना — मुआवजा दावा",
        "icon": "🚑",
        "questions": [
            {"id": "q1", "text": "Was the FIR filed at the police station?",
             "text_ta": "காவல் நிலையத்தில் FIR பதிவு செய்யப்பட்டதா?",
             "text_hi": "क्या पुलिस स्टेशन में FIR दर्ज की गई?",
             "type": "boolean"},
            {"id": "q2", "text": "Do you have the other vehicle's registration number?",
             "text_ta": "மற்ற வாகனத்தின் பதிவு எண் உங்களிடம் உள்ளதா?",
             "text_hi": "क्या आपके पास दूसरे वाहन का पंजीकरण नंबर है?",
             "type": "boolean"},
            {"id": "q3", "text": "Did you seek medical treatment immediately?",
             "text_ta": "நீங்கள் உடனடியாக மருத்துவ சிகிச்சை பெற்றீர்களா?",
             "text_hi": "क्या आपने तुरंत चिकित्सा उपचार लिया?",
             "type": "boolean"},
            {"id": "q4", "text": "Was the accident caused by negligence of the other driver?",
             "text_ta": "விபத்து மற்ற ஓட்டுநரின் அலட்சியத்தால் ஏற்பட்டதா?",
             "text_hi": "क्या दुर्घटना दूसरे चालक की लापरवाही के कारण हुई?",
             "type": "boolean"},
        ],
    },
    {
        "scenario_id": "traffic_challan",
        "category": "traffic",
        "title": "Unfair traffic challan / e-challan dispute",
        "title_ta": "நியாயமற்ற ட்ராஃபிக் சலான் / வாக",
        "title_hi": "अनुचित यातायात चालान विवाद",
        "icon": "📋",
        "questions": [
            {"id": "q1", "text": "Was the challan issued by a physical officer or automatically?",
             "text_ta": "சலான் ஒரு அதிகாரியால் வழங்கப்பட்டதா அல்லது தானாகவா?",
             "text_hi": "क्या चालान एक अधिकारी द्वारा जारी किया गया या स्वचालित रूप से?",
             "type": "choice",
             "options": ["Physical officer", "E-challan / Camera", "Not sure"]},
            {"id": "q2", "text": "Do you believe you were not at fault?",
             "text_ta": "நீங்கள் தவறு செய்யவில்லை என்று நம்புகிறீர்களா?",
             "text_hi": "क्या आप मानते हैं कि आप दोषी नहीं थे?",
             "type": "boolean"},
            {"id": "q3", "text": "Do you have evidence (dashcam, witnesses)?",
             "text_ta": "உங்களிடம் ஆதாரம் உள்ளதா (டாஷ்கேம், சாட்சிகள்)?",
             "text_hi": "क्या आपके पास सबूत (डैशकैम, गवाह) हैं?",
             "type": "boolean"},
        ],
    },

    # ===== WOMEN SAFETY =====
    {
        "scenario_id": "women_dv",
        "category": "women",
        "title": "Domestic violence / abuse",
        "title_ta": "குடும்ப வன்முறை / துன்புறுத்தல்",
        "title_hi": "घरेलू हिंसा / दुर्व्यवहार",
        "icon": "🛡️",
        "questions": [
            {"id": "q1", "text": "Are you currently in a safe place?",
             "text_ta": "நீங்கள் இப்போது பாதுகாப்பான இடத்தில் இருக்கிறீர்களா?",
             "text_hi": "क्या आप अभी सुरक्षित स्थान पर हैं?",
             "type": "boolean"},
            {"id": "q2", "text": "Have you experienced physical, emotional, or financial abuse?",
             "text_ta": "நீங்கள் உடல், மன, அல்லது நிதி ரீதியான துன்புறுத்தலை அனுபவித்தீர்களா?",
             "text_hi": "क्या आपने शारीरिक, भावनात्मक या वित्तीय दुर्व्यवहार का अनुभव किया?",
             "type": "boolean"},
            {"id": "q3", "text": "Do you have children living in this home?",
             "text_ta": "இந்த வீட்டில் வாழும் குழந்தைகள் உங்களிடம் உள்ளனவா?",
             "text_hi": "क्या इस घर में रहने वाले बच्चे हैं?",
             "type": "boolean"},
            {"id": "q4", "text": "Do you have any medical certificates / photographs of injuries?",
             "text_ta": "காயங்களின் மருத்துவ சான்றிதழ்கள் / புகைப்படங்கள் உங்களிடம் உள்ளனவா?",
             "text_hi": "क्या आपके पास चोटों के मेडिकल प्रमाणपत्र / फोटोग्राफ हैं?",
             "type": "boolean"},
        ],
    },
    {
        "scenario_id": "women_workplace",
        "category": "women",
        "title": "Workplace sexual harassment",
        "title_ta": "பணியிட பாலியல் துன்புறுத்தல்",
        "title_hi": "कार्यस्थल यौन उत्पीड़न",
        "icon": "⚖️",
        "questions": [
            {"id": "q1", "text": "Does your employer have an Internal Complaints Committee (ICC)?",
             "text_ta": "உங்கள் நிறுவனத்தில் உள் புகார் குழு (ICC) உள்ளதா?",
             "text_hi": "क्या आपके नियोक्ता के पास आंतरिक शिकायत समिति (ICC) है?",
             "type": "boolean"},
            {"id": "q2", "text": "Have you filed a complaint with ICC or HR?",
             "text_ta": "நீங்கள் ICC அல்லது HR-இல் புகாரளித்தீர்களா?",
             "text_hi": "क्या आपने ICC या HR में शिकायत दर्ज की है?",
             "type": "boolean"},
            {"id": "q3", "text": "Did the incident occur in the last 3 months?",
             "text_ta": "சம்பவம் கடந்த 3 மாதங்களில் நடந்ததா?",
             "text_hi": "क्या घटना पिछले 3 महीनों में हुई?",
             "type": "boolean"},
            {"id": "q4", "text": "Do you have messages, emails, or witnesses as evidence?",
             "text_ta": "உங்களிடம் ஆதாரமாக செய்திகள், மின்னஞ்சல்கள் அல்லது சாட்சிகள் உள்ளனவா?",
             "text_hi": "क्या आपके पास सबूत के रूप में संदेश, ईमेल या गवाह हैं?",
             "type": "boolean"},
        ],
    },

    # ===== EDUCATION =====
    {
        "scenario_id": "education_admission",
        "category": "education",
        "title": "Wrongful admission denial / quota issues",
        "title_ta": "சேர்க்கை மறுப்பு / ஒதுக்கீடு சிக்கல்கள்",
        "title_hi": "प्रवेश से इनकार / आरक्षण मुद्दे",
        "icon": "🏫",
        "questions": [
            {"id": "q1", "text": "Is this for school (RTE) or college/university admission?",
             "text_ta": "இது பள்ளி (RTE) சேர்க்கையா அல்லது கல்லூரி சேர்க்கையா?",
             "text_hi": "क्या यह स्कूल (RTE) या कॉलेज/विश्वविद्यालय प्रवेश के लिए है?",
             "type": "choice",
             "options": ["School (RTE Act)", "College / University", "Professional course"]},
            {"id": "q2", "text": "Did you receive written rejection from the institution?",
             "text_ta": "நிறுவனத்திடம் எழுத்துறு நிராகரிப்பு கிடைத்ததா?",
             "text_hi": "क्या आपको संस्था से लिखित अस्वीकृति मिली?",
             "type": "boolean"},
            {"id": "q3", "text": "Are you applying under a reserved category (SC/ST/OBC)?",
             "text_ta": "நீங்கள் இட ஒதுக்கீடு வகையில் (SC/ST/OBC) விண்ணப்பிக்கிறீர்களா?",
             "text_hi": "क्या आप आरक्षित श्रेणी (SC/ST/OBC) में आवेदन कर रहे हैं?",
             "type": "boolean"},
        ],
    },
    {
        "scenario_id": "education_fee",
        "category": "education",
        "title": "School/college refusing fee refund",
        "title_ta": "கல்வி கட்டணம் திரும்பத் தர மறுப்பு",
        "title_hi": "स्कूल/कॉलेज शुल्क वापसी से इनकार",
        "icon": "💰",
        "questions": [
            {"id": "q1", "text": "Did you cancel admission before the academic year started?",
             "text_ta": "கல்வியாண்டு தொடங்குவதற்கு முன் சேர்க்கையை ரத்து செய்தீர்களா?",
             "text_hi": "क्या आपने शैक्षणिक वर्ष शुरू होने से पहले प्रवेश रद्द किया?",
             "type": "boolean"},
            {"id": "q2", "text": "Did you get a receipt for fees paid?",
             "text_ta": "செலுத்திய கட்டணங்களுக்கு ரசீது கிடைத்ததா?",
             "text_hi": "क्या आपको भुगतान की गई फीस की रसीद मिली?",
             "type": "boolean"},
            {"id": "q3", "text": "Is the institution approved by UGC/AICTE or government?",
             "text_ta": "நிறுவனம் UGC/AICTE அல்லது அரசாங்கத்தால் அங்கீகரிக்கப்பட்டதா?",
             "text_hi": "क्या संस्था UGC/AICTE या सरकार द्वारा अनुमोदित है?",
             "type": "boolean"},
        ],
    },

    # ===== CHEQUE BOUNCE & DEBT =====
    {
        "scenario_id": "cheque_bounce_138",
        "category": "cheque_debt",
        "title": "Dishonoured Cheque (Section 138 NI Act)",
        "title_ta": "செக் திரும்பல் (பிரிவு 138 NI சட்டம்)",
        "title_hi": "चेक बाउंस (धारा 138 एनआई अधिनियम)",
        "icon": "💳",
        "questions": [
            {"id": "q1", "text": "What was the reason stated in the cheque return memo?",
             "text_ta": "செக் திரும்பியதற்கான காரணம் என்ன?",
             "text_hi": "चेक वापसी मेमो में क्या कारण बताया गया?",
             "type": "choice",
             "options": ["Insufficient Funds", "Signature Mismatch", "Account Closed", "Stop Payment by Drawer"]},
            {"id": "q2", "text": "Has it been less than 30 days since you received the bank bounce memo?",
             "text_ta": "வங்கி மெமோ கிடைத்து 30 நாட்களுக்குள் உள்ளதா?",
             "text_hi": "क्या आपको बैंक बाउंस मेमो मिले 30 दिन से कम हुए हैं?",
             "type": "boolean"},
            {"id": "q3", "text": "Have you sent a formal 15-day statutory legal notice to the drawer?",
             "text_ta": "செக் வழங்கியவருக்கு 15 நாள் நோட்டீஸ் அனுப்பினீர்களா?",
             "text_hi": "क्या आपने ड्रावर को औपचारिक 15-दिवसीय कानूनी नोटिस भेजा है?",
             "type": "boolean"},
            {"id": "q4", "text": "Was the cheque issued to discharge a legally enforceable debt?",
             "text_ta": "செக் சட்டப்பூர்வ கடனுக்காக வழங்கப்பட்டதா?",
             "text_hi": "क्या चेक कानूनी रूप से लागू करने योग्य ऋण के लिए जारी किया गया था?",
             "type": "boolean"},
        ],
    },

    # ===== RTI & PUBLIC SERVICE =====
    {
        "scenario_id": "rti_filing",
        "category": "rti",
        "title": "RTI Application & Appeal Process",
        "title_ta": "RTI விண்ணப்பம் மற்றும் மேல்முறையீடு",
        "title_hi": "RTI आवेदन और अपील प्रक्रिया",
        "icon": "📜",
        "questions": [
            {"id": "q1", "text": "Which public authority holds the information?",
             "text_ta": "எந்த அரசு அமைப்பிடம் தகவல் உள்ளது?",
             "text_hi": "किस सार्वजनिक प्राधिकरण के पास जानकारी है?",
             "type": "choice",
             "options": ["Central Govt / Ministry", "State Govt Department", "Municipal Corporation / Panchayat", "Public Sector Bank / University"]},
            {"id": "q2", "text": "Has it been more than 30 days since submitting your RTI application?",
             "text_ta": "RTI விண்ணப்பம் சமர்ப்பித்து 30 நாட்களுக்கு மேல் ஆகிவிட்டதா?",
             "text_hi": "क्या RTI आवेदन जमा किए 30 दिन से अधिक हो गए हैं?",
             "type": "boolean"},
            {"id": "q3", "text": "Did the Public Information Officer (PIO) refuse or give incomplete info?",
             "text_ta": "PIO தகவல் தர மறுத்தாரா அல்லது அரைகுறையாக தந்தாரா?",
             "text_hi": "क्या PIO ने जानकारी देने से इनकार किया या अधूरी जानकारी दी?",
             "type": "boolean"},
        ],
    },

    # ===== RERA REAL ESTATE =====
    {
        "scenario_id": "rera_delay",
        "category": "real_estate",
        "title": "Delay in Flat / Plot Possession (RERA)",
        "title_ta": "வீடு ஒப்படைப்பில் தாமதம் (RERA)",
        "title_hi": "फ्लैट/प्लॉट कब्जे में देरी (रेरा)",
        "icon": "🏢",
        "questions": [
            {"id": "q1", "text": "Is the builder project registered under RERA?",
             "text_ta": "கட்டிட திட்டம் RERA-வில் பதிவு செய்யப்பட்டுள்ளதா?",
             "text_hi": "क्या बिल्डर प्रोजेक्ट रेरा के तहत पंजीकृत है?",
             "type": "boolean"},
            {"id": "q2", "text": "Has the promised possession date in Builder-Buyer Agreement passed?",
             "text_ta": "ஒப்பந்தத்தில் கூறிய ஒப்படைப்பு தேதி கடந்துவிட்டதா?",
             "text_hi": "क्या समझौते में वादा की गई कब्जा तिथि बीत चुकी है?",
             "type": "boolean"},
            {"id": "q3", "text": "What remedy are you seeking?",
             "text_ta": "நீங்கள் என்ன தீர்வு எதிர்பார்க்கிறீர்கள்?",
             "text_hi": "आप क्या उपाय चाहते हैं?",
             "type": "choice",
             "options": ["Full refund with interest", "Monthly delay compensation / interest", "Immediate possession order"]},
        ],
    },

    # ===== INSURANCE & HEALTH =====
    {
        "scenario_id": "insurance_rejection",
        "category": "insurance",
        "title": "Wrongful Rejection of Insurance Claim",
        "title_ta": "காப்பீட்டு கோரிக்கை நிராகரிப்பு",
        "title_hi": "बीमा दावे का गलत निरस्तीकरण",
        "icon": "🏥",
        "questions": [
            {"id": "q1", "text": "What type of insurance policy is this?",
             "text_ta": "இது எந்த வகை காப்பீடு?",
             "text_hi": "यह किस प्रकार की बीमा पॉलिसी है?",
             "type": "choice",
             "options": ["Health / Mediclaim", "Motor / Vehicle", "Life Insurance", "Property / Business"]},
            {"id": "q2", "text": "Did the insurer cite 'Pre-existing illness' or 'Delay in intimation'?",
             "text_ta": "முந்தைய நோய் அல்லது தாமதம் என காரணம் கூறினார்களா?",
             "text_hi": "क्या बीमाकर्ता ने 'पूर्व बीमारी' या 'सूचना में देरी' का कारण बताया?",
             "type": "boolean"},
            {"id": "q3", "text": "Have you submitted a formal written grievance to the insurer's Grievance Officer?",
             "text_ta": "நிறுவனத்தின் புகார் அதிகாரியிடம் எழுத்தில் புகாரளித்தீர்களா?",
             "text_hi": "क्या आपने बीमाकर्ता के शिकायत अधिकारी को लिखित शिकायत दी है?",
             "type": "boolean"},
        ],
    },

    # ===== FAMILY & SUPPORT =====
    {
        "scenario_id": "family_maintenance",
        "category": "family",
        "title": "Maintenance & Support (Sec 125 CrPC / BNSS)",
        "title_ta": "ஜீவனாம்சம் மற்றும் பராமரிப்பு",
        "title_hi": "भरण-पोषण और सहायता (धारा 125)",
        "icon": "👨‍👩‍👧",
        "questions": [
            {"id": "q1", "text": "Who is claiming monthly maintenance support?",
             "text_ta": "யார் பராமரிப்பு உதவி கோருகிறார்கள்?",
             "text_hi": "मासिक भरण-पोषण सहायता का दावा कौन कर रहा है?",
             "type": "choice",
             "options": ["Wife", "Minor / Dependent Child", "Elderly Parent"]},
            {"id": "q2", "text": "Does the person claiming maintenance have independent monthly income?",
             "text_ta": "கோருபவருக்கு சொந்த மாத வருமானம் உள்ளதா?",
             "text_hi": "क्या दावा करने वाले व्यक्ति की स्वतंत्र मासिक आय है?",
             "type": "boolean"},
            {"id": "q3", "text": "Has the respondent refused or neglected to maintain despite having sufficient means?",
             "text_ta": "வசதி இருந்தும் பராமரிக்க மறுத்தாரா?",
             "text_hi": "क्या पर्याप्त साधन होने के बावजूद उत्तरदाता ने भरण-पोषण से इनकार किया?",
             "type": "boolean"},
        ],
    },
]


def get_categories() -> list[dict]:
    return CATEGORIES


def get_scenarios_by_category(category: str) -> list[dict]:
    return [s for s in SCENARIOS if s["category"] == category]


def get_scenario(scenario_id: str) -> dict | None:
    for s in SCENARIOS:
        if s["scenario_id"] == scenario_id:
            return s
    return None
